# Generated by Django 6.0.3 on 2026-04-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'advertisements',
            },
        ),
    ]
