# Generated by Django 6.0.3 on 2026-03-21 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=600)),
                ('original_file_type', models.CharField(max_length=10)),
                ('original_file_size', models.PositiveIntegerField()),
                ('new_filename', models.CharField(max_length=600)),
                ('new_file_type', models.CharField(max_length=10)),
                ('new_file_size', models.PositiveIntegerField()),
                ('new_file_path', models.FileField(upload_to='history/')),
                ('end_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
